name: Release Workflow

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - develop # Trigger the workflow on changes to the develop branch

jobs:
  merge-develop-into-main:
    name: Merge Develop into Main
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all history is fetched for merging

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Merge develop into main
      - name: Merge Develop into Main
        run: |
          git checkout main
          git merge develop --no-edit

      # Push the merged main branch back to the repository
      - name: Push Changes to Main
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-vsix:
    name: Build VSIX
    runs-on: ubuntu-latest
    needs: merge-develop-into-main

    steps:
      # Checkout the main branch
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use the latest LTS version

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: |
          npx vscode-test --disable-gpu --no-sandbox


      # Compile the extension
      - name: Compile Extension
        run: npm run compile

      # Package the extension as a VSIX file
      - name: Package Extension
        run: |
          npm install -g vsce
          vsce package
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      # Upload the VSIX file
      - name: Upload VSIX File
        uses: actions/upload-artifact@v3
        with:
          name: mkh-codeformatter.vsix
          path: "*.vsix"

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-vsix

    steps:
      # Checkout the repository
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Create a GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          body: "Automated release of mkhCodeFormatter by Mustafa Kamal Hossain."
          draft: false
          prerelease: false
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
